nginx1:
  mem_limit: 128m
  ports:
    - 8001:80
  expose:
    - 8001
  restart: always

nginx2:
  mem_limit: 128m
  ports:
    - 8002:80
  expose:
    - 8002
  restart: always

# Kong Database
kong-database:
  image: postgres:9.4
  ports:
    - 5432
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong

# Kong
kong:
  image: kong
  links:
    - kong-database:kong-database
  ports:
    - 8000
    - 8443
    - 8001
  expose:
    - 7946
    - 7946/udp
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database