springdata:
  image: goodraincloudframeworks/springdata
  ports:
    - 8080:8080

kong-database:
  image: postgres
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong

kong:
  image: kong
  links:
    - kong-database:kong-database
  ports:
    - 8000
    - 8443
    - 8001
  expose:
    - 7946
    - 7946/udp
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database

kong-dashboard:
  image: woodyalen202/docker-kong-dashboard
  ports:
    - 5000:5000
