nginx1:
  mem_limit: 128m
  ports:
    - 9001:80
  restart: always

nginx2:
  mem_limit: 128m
  ports:
    - 9002:80
  restart: always

# Kong Database
kong-database:
  image: postgres
  ports:
    - 5432
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong

# Kong
kong:
  image: kong
  links:
    - kong-database:kong-database
  ports:
    - 8000
    - 8443
    - 8001
  expose:
    - 7946
    - 7946/udp
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database

# Kong dashboard
kong:
  image: woodyalen202/docker-kong-dashboard
  ports:
    - 5000:8080
